name = "TBDjulia"
uuid = "1782813c-a33e-4561-9107-676f32f77845"
authors = ["Ewa Kasprzak"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
