name: TBD Julia CI/CD Workflow

on: 
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.6'

      - name: Cache Julia packages
        uses: julia-actions/cache@v2
        with:
          path: ~/.julia/artifacts,~/.julia/packages
          key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-
            
      - name: Build package
        uses: julia-actions/julia-buildpkg@v1
        with:
          project: TBD

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
        with:
          project: TBD
