name: Julia CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.11.6'

    - name: Install dependencies
      run: julia --project=TBD -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

    - name: Run tests
      run: chmod +x TBD/utils/scripts/test.sh && ./TBD/utils/scripts/test.sh
